version: "3.1"

services:
  https-portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontend
    environment:
      DOMAINS: "socks-market.pl -> http://frontend:${FRONTEND_PORT}"
      # STAGE: "production"
      # FORCE_RENEW: "true"

    volumes:
      - https-portal-data:/var/lib/https-portal

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      args:
        - BROWSER=${BROWSER}
        - PORT=${FRONTEND_PORT}
        - REACT_APP_IP=${REACT_BACKEND_APP_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: always

volumes:
  https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
